server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Serve static files
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Gzip
    gzip on;
    gzip_types text/html text/css application/javascript;

    # Cache static assets
    location ~* \.(css|js|woff2|png|svg)$ {
        expires 1h;
        add_header Cache-Control "public";
    }
}
